#!/bin/bash
# build.sh — Build script for PS2 AthenaEnv port
# Prepares assets and creates a deployable PS2 package
#
# Prerequisites:
#   - AthenaEnv v4 SDK installed
#   - ffmpeg (for audio conversion)
#   - ImageMagick or similar (for atlas conversion)
#   - mkisofs or genisoimage (for ISO creation)
#
# Usage:
#   cd src/ps2/deploy
#   ./build.sh [--iso]
#
# Output:
#   build/         — Ready-to-run directory for PS2
#   build.iso      — PS2 bootable ISO (if --iso flag passed)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
PS2_SRC="$PROJECT_ROOT/src/ps2"
WEB_ASSETS="$PROJECT_ROOT/assets"
BUILD_DIR="$SCRIPT_DIR/build"
BUILD_ISO=false

if [ "$1" = "--iso" ]; then
    BUILD_ISO=true
fi

echo "=== PS2 AthenaEnv Build ==="
echo "Project root: $PROJECT_ROOT"
echo "Build dir: $BUILD_DIR"

# Clean build directory
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/assets/sounds"
mkdir -p "$BUILD_DIR/assets/sounds/scene_continue"
mkdir -p "$BUILD_DIR/assets/sounds/scene_game"
mkdir -p "$BUILD_DIR/assets/img/stage"
mkdir -p "$BUILD_DIR/src/ps2"

# Copy AthenaEnv ELF
if [ -f "$PS2_SRC/athena.elf" ]; then
    cp "$PS2_SRC/athena.elf" "$BUILD_DIR/athena.elf"
    echo "  Copied athena.elf"
else
    echo "  WARN: athena.elf not found at $PS2_SRC/athena.elf"
fi

# --- Step 1: Bundle JS files ---
echo "[1/5] Bundling JavaScript..."

JS_FILES=(
    "constants.js"
    "game_state.js"
    "atlas.js"
    "draw.js"
    "sprite.js"
    "tween.js"
    "timer.js"
    "sound.js"
    "input.js"
    "hud.js"
    "projectile.js"
    "player.js"
    "enemy.js"
    "boss.js"
    "scenes.js"
    "scene_title.js"
    "scene_adv.js"
    "scene_game.js"
    "scene_continue.js"
    "scene_ending.js"
)

# Create bundled main.js (all modules concatenated)
BUNDLE="$BUILD_DIR/main.js"
echo "// PS2 STG - AthenaEnv Port (bundled)" > "$BUNDLE"
echo "// Auto-generated by build.sh" >> "$BUNDLE"
echo "" >> "$BUNDLE"

for f in "${JS_FILES[@]}"; do
    echo "// === $f ===" >> "$BUNDLE"
    cat "$PS2_SRC/$f" >> "$BUNDLE"
    echo "" >> "$BUNDLE"
done

# Append the main loop (without the module loading section)
echo "// === main entry ===" >> "$BUNDLE"
# Extract main.js content after the module loading IIFE
sed -n '/^\/\/ --- Asset Loading ---$/,$p' "$PS2_SRC/main.js" >> "$BUNDLE"

echo "  Bundled $(wc -l < "$BUNDLE") lines"

# --- Step 2: Process texture atlases (downscale for PS2 memory) ---
echo "[2/5] Processing texture atlases..."

# PS2 has only 4MB GS VRAM shared with framebuffers.
# Textures must be small enough to fit alongside the display buffers.
# Target 512x512 max (~1MB RGBA per texture).
PS2_MAX_TEX=512

PS2_ASSETS="$PS2_SRC/assets"

for atlas in game_ui game_asset; do
    JSON_SRC="$WEB_ASSETS/${atlas}.json"
    PNG_SRC="$WEB_ASSETS/img/${atlas}.png"
    JSON_DST="$BUILD_DIR/assets/${atlas}.json"
    PNG_DST="$BUILD_DIR/assets/${atlas}.png"

    if [ ! -f "$JSON_SRC" ]; then
        echo "  WARN: $JSON_SRC not found, skipping"
        continue
    fi

    if [ ! -f "$PNG_SRC" ]; then
        echo "  WARN: $PNG_SRC not found, skipping"
        continue
    fi

    python3 - "$PNG_SRC" "$JSON_SRC" "$PNG_DST" "$JSON_DST" "$PS2_MAX_TEX" << 'PYEOF'
import sys, json
from PIL import Image

png_src, json_src, png_dst, json_dst, max_tex = sys.argv[1:6]
max_tex = int(max_tex)

img = Image.open(png_src)
orig_w, orig_h = img.size

scale = min(1.0, max_tex / orig_w, max_tex / orig_h)

if scale < 1.0:
    new_w = int(orig_w * scale)
    new_h = int(orig_h * scale)
    img = img.resize((new_w, new_h), Image.LANCZOS)
    print(f"  Downscaled {png_src.split('/')[-1]}: {orig_w}x{orig_h} -> {new_w}x{new_h} (scale={scale:.3f})")
else:
    print(f"  {png_src.split('/')[-1]}: {orig_w}x{orig_h} (no resize needed)")

img.save(png_dst, "PNG")

with open(json_src) as f:
    data = json.load(f)

if scale < 1.0:
    if isinstance(data.get("frames"), list):
        for fr in data["frames"]:
            r = fr["frame"]
            r["x"] = round(r["x"] * scale)
            r["y"] = round(r["y"] * scale)
            r["w"] = max(1, round(r["w"] * scale))
            r["h"] = max(1, round(r["h"] * scale))
            if "spriteSourceSize" in fr:
                s = fr["spriteSourceSize"]
                s["x"] = round(s["x"] * scale)
                s["y"] = round(s["y"] * scale)
                s["w"] = max(1, round(s["w"] * scale))
                s["h"] = max(1, round(s["h"] * scale))
            if "sourceSize" in fr:
                ss = fr["sourceSize"]
                ss["w"] = max(1, round(ss["w"] * scale))
                ss["h"] = max(1, round(ss["h"] * scale))
    elif isinstance(data.get("frames"), dict):
        for key, val in data["frames"].items():
            r = val["frame"]
            r["x"] = round(r["x"] * scale)
            r["y"] = round(r["y"] * scale)
            r["w"] = max(1, round(r["w"] * scale))
            r["h"] = max(1, round(r["h"] * scale))
            if "spriteSourceSize" in val:
                s = val["spriteSourceSize"]
                s["x"] = round(s["x"] * scale)
                s["y"] = round(s["y"] * scale)
                s["w"] = max(1, round(s["w"] * scale))
                s["h"] = max(1, round(s["h"] * scale))
            if "sourceSize" in val:
                ss = val["sourceSize"]
                ss["w"] = max(1, round(ss["w"] * scale))
                ss["h"] = max(1, round(ss["h"] * scale))

    if "meta" in data and "size" in data["meta"]:
        data["meta"]["size"]["w"] = round(data["meta"]["size"]["w"] * scale)
        data["meta"]["size"]["h"] = round(data["meta"]["size"]["h"] * scale)

    # Store inverse scale so runtime can restore original display sizes
    if "meta" not in data:
        data["meta"] = {}
    data["meta"]["ps2DisplayScale"] = round(1.0 / scale, 4)

with open(json_dst, "w") as f:
    json.dump(data, f)

print(f"  Wrote {json_dst.split('/')[-1]} (scaled coords, displayScale={1.0/scale:.2f}x)")
PYEOF
done

# Process level_2028 atlas (same downscaling as above)
for atlas in level_2028_atlas; do
    JSON_SRC="$PS2_ASSETS/${atlas}.json"
    PNG_SRC="$PS2_ASSETS/${atlas}.png"
    JSON_DST="$BUILD_DIR/assets/${atlas}.json"
    PNG_DST="$BUILD_DIR/assets/${atlas}.png"

    if [ ! -f "$JSON_SRC" ] || [ ! -f "$PNG_SRC" ]; then
        echo "  WARN: $atlas source files not found in $PS2_ASSETS, skipping"
    else
        python3 - "$PNG_SRC" "$JSON_SRC" "$PNG_DST" "$JSON_DST" "$PS2_MAX_TEX" << 'PYEOF'
import sys, json
from PIL import Image

png_src, json_src, png_dst, json_dst, max_tex = sys.argv[1:6]
max_tex = int(max_tex)

img = Image.open(png_src)
orig_w, orig_h = img.size

scale = min(1.0, max_tex / orig_w, max_tex / orig_h)

if scale < 1.0:
    new_w = int(orig_w * scale)
    new_h = int(orig_h * scale)
    img = img.resize((new_w, new_h), Image.LANCZOS)
    print(f"  Downscaled {png_src.split('/')[-1]}: {orig_w}x{orig_h} -> {new_w}x{new_h} (scale={scale:.3f})")
else:
    print(f"  {png_src.split('/')[-1]}: {orig_w}x{orig_h} (no resize needed)")

img.save(png_dst, "PNG")

with open(json_src) as f:
    data = json.load(f)

if scale < 1.0:
    if isinstance(data.get("frames"), list):
        for fr in data["frames"]:
            r = fr["frame"]
            r["x"] = round(r["x"] * scale)
            r["y"] = round(r["y"] * scale)
            r["w"] = max(1, round(r["w"] * scale))
            r["h"] = max(1, round(r["h"] * scale))
            if "spriteSourceSize" in fr:
                s = fr["spriteSourceSize"]
                s["x"] = round(s["x"] * scale)
                s["y"] = round(s["y"] * scale)
                s["w"] = max(1, round(s["w"] * scale))
                s["h"] = max(1, round(s["h"] * scale))
            if "sourceSize" in fr:
                ss = fr["sourceSize"]
                ss["w"] = max(1, round(ss["w"] * scale))
                ss["h"] = max(1, round(ss["h"] * scale))
    elif isinstance(data.get("frames"), dict):
        for key, val in data["frames"].items():
            r = val["frame"]
            r["x"] = round(r["x"] * scale)
            r["y"] = round(r["y"] * scale)
            r["w"] = max(1, round(r["w"] * scale))
            r["h"] = max(1, round(r["h"] * scale))
            if "spriteSourceSize" in val:
                s = val["spriteSourceSize"]
                s["x"] = round(s["x"] * scale)
                s["y"] = round(s["y"] * scale)
                s["w"] = max(1, round(s["w"] * scale))
                s["h"] = max(1, round(s["h"] * scale))
            if "sourceSize" in val:
                ss = val["sourceSize"]
                ss["w"] = max(1, round(ss["w"] * scale))
                ss["h"] = max(1, round(ss["h"] * scale))

    if "meta" in data and "size" in data["meta"]:
        data["meta"]["size"]["w"] = round(data["meta"]["size"]["w"] * scale)
        data["meta"]["size"]["h"] = round(data["meta"]["size"]["h"] * scale)

    if "meta" not in data:
        data["meta"] = {}
    data["meta"]["ps2DisplayScale"] = round(1.0 / scale, 4)

with open(json_dst, "w") as f:
    json.dump(data, f)

print(f"  Wrote {json_dst.split('/')[-1]} (scaled coords, displayScale={1.0/scale:.2f}x)")
PYEOF
    fi
done

# Copy level_2028 Firebase level data
if [ -f "$PS2_ASSETS/level_2028.json" ]; then
    cp "$PS2_ASSETS/level_2028.json" "$BUILD_DIR/assets/level_2028.json"
    echo "  Copied level_2028.json"
fi

# Copy cyber-liberty player spritesheet (small enough, no downscale needed)
if [ -f "$PS2_ASSETS/cyber-liberty.png" ]; then
    cp "$PS2_ASSETS/cyber-liberty.png" "$BUILD_DIR/assets/cyber-liberty.png"
    echo "  Copied cyber-liberty.png"
fi

# Copy game recipe
if [ -f "$WEB_ASSETS/game.json" ]; then
    cp "$WEB_ASSETS/game.json" "$BUILD_DIR/assets/game.json"
    echo "  Copied game.json"
fi

# --- Step 3: Convert audio ---
echo "[3/5] Converting audio files..."

convert_audio() {
    local src="$1"
    local dst="$2"
    local fmt="$3"

    if [ ! -f "$src" ]; then
        echo "  SKIP: $src (not found)"
        return
    fi

    if command -v ffmpeg &>/dev/null; then
        if [ "$fmt" = "wav" ]; then
            ffmpeg -y -i "$src" -acodec pcm_s16le -ar 22050 -ac 1 "$dst" 2>/dev/null
        elif [ "$fmt" = "ogg" ]; then
            ffmpeg -y -i "$src" -acodec libvorbis -ar 44100 -ac 2 -q:a 4 "$dst" 2>/dev/null
        fi
        echo "  Converted: $(basename "$dst")"
    else
        echo "  SKIP: ffmpeg not found, cannot convert $(basename "$src")"
    fi
}

# Convert SFX to WAV (22kHz mono for PS2 memory)
SFX_LIST=(
    "se_shoot" "se_shoot_b" "se_explosion" "se_damage" "se_guard"
    "se_sp" "se_sp_explosion" "se_barrier_start" "se_barrier_end"
    "se_decision" "se_correct" "se_cursor" "se_over"
    "se_finish_akebono"
)
for sfx in "${SFX_LIST[@]}"; do
    convert_audio "$WEB_ASSETS/sounds/${sfx}.mp3" "$BUILD_DIR/assets/sounds/${sfx}.wav" "wav"
done

# Convert voice clips to WAV
VOICE_LIST=(
    "voice_titlecall" "voice_fight" "voice_ko" "voice_another_fighter"
    "voice_congra" "voice_gameover" "voice_thankyou"
    "voice_round0" "voice_round1" "voice_round2" "voice_round3"
    "g_damage_voice" "g_powerup_voice" "g_sp_voice"
    "g_adbenture_voice0"
)
for v in "${VOICE_LIST[@]}"; do
    src_path="$WEB_ASSETS/sounds/${v}.mp3"
    if [ ! -f "$src_path" ]; then
        # Try subdirectory patterns
        for subdir in scene_title scene_adventure scene_game scene_clear ui; do
            if [ -f "$WEB_ASSETS/sounds/${subdir}/${v}.mp3" ]; then
                src_path="$WEB_ASSETS/sounds/${subdir}/${v}.mp3"
                break
            fi
        done
    fi
    convert_audio "$src_path" "$BUILD_DIR/assets/sounds/${v}.wav" "wav"
done

# Continue scene voices
for i in $(seq 0 9); do
    convert_audio "$WEB_ASSETS/sounds/scene_continue/voice_countdown${i}.mp3" \
        "$BUILD_DIR/assets/sounds/scene_continue/voice_countdown${i}.wav" "wav"
done
for i in 0 1 2; do
    convert_audio "$WEB_ASSETS/sounds/scene_continue/g_continue_yes_voice${i}.mp3" \
        "$BUILD_DIR/assets/sounds/scene_continue/g_continue_yes_voice${i}.wav" "wav"
done
for i in 0 1; do
    convert_audio "$WEB_ASSETS/sounds/scene_continue/g_continue_no_voice${i}.mp3" \
        "$BUILD_DIR/assets/sounds/scene_continue/g_continue_no_voice${i}.wav" "wav"
done

# Stage voices
for i in $(seq 0 4); do
    convert_audio "$WEB_ASSETS/sounds/scene_game/g_stage_voice_${i}.mp3" \
        "$BUILD_DIR/assets/sounds/scene_game/g_stage_voice_${i}.wav" "wav"
done

# Boss voices and BGM
BOSS_NAMES=("bison" "barlog" "sagat" "vega" "goki" "fang")
for bn in "${BOSS_NAMES[@]}"; do
    convert_audio "$WEB_ASSETS/sounds/boss_${bn}_voice_add.mp3" \
        "$BUILD_DIR/assets/sounds/boss_${bn}_voice_add.wav" "wav"
    convert_audio "$WEB_ASSETS/sounds/boss_${bn}_voice_ko.mp3" \
        "$BUILD_DIR/assets/sounds/boss_${bn}_voice_ko.wav" "wav"
    convert_audio "$WEB_ASSETS/sounds/boss_${bn}_bgm.mp3" \
        "$BUILD_DIR/assets/sounds/boss_${bn}_bgm.ogg" "ogg"
done

# Other BGM
convert_audio "$WEB_ASSETS/sounds/scene_adventure/adventure_bgm.mp3" \
    "$BUILD_DIR/assets/sounds/adventure_bgm.ogg" "ogg"
convert_audio "$WEB_ASSETS/sounds/scene_continue/bgm_continue.mp3" \
    "$BUILD_DIR/assets/sounds/bgm_continue.ogg" "ogg"
convert_audio "$WEB_ASSETS/sounds/scene_continue/bgm_gameover.mp3" \
    "$BUILD_DIR/assets/sounds/bgm_gameover.ogg" "ogg"

# --- Step 4: Copy stage backgrounds ---
echo "[4/5] Copying stage backgrounds..."

for i in $(seq 0 4); do
    for type in loop end; do
        if [ -f "$WEB_ASSETS/img/stage/stage_${type}${i}.png" ]; then
            cp "$WEB_ASSETS/img/stage/stage_${type}${i}.png" "$BUILD_DIR/assets/img/stage/"
            echo "  Copied stage_${type}${i}.png"
        fi
    done
done

if [ -f "$WEB_ASSETS/img/title_bg.jpg" ]; then
    if command -v convert &>/dev/null; then
        convert "$WEB_ASSETS/img/title_bg.jpg" "$BUILD_DIR/assets/img/title_bg.png"
    else
        cp "$WEB_ASSETS/img/title_bg.jpg" "$BUILD_DIR/assets/img/title_bg.jpg"
    fi
fi

# --- Step 5: Create AthenaEnv boot config ---
echo "[5/5] Creating boot configuration..."

# SYSTEM.CNF — PS2 boot descriptor (ATHA_000.01 = athena.elf renamed for ISO 8.3)
cat > "$BUILD_DIR/SYSTEM.CNF" << 'EOF'
BOOT2 = cdrom0:\ATHA_000.01;1
VER = 1.00
VMODE = NTSC
EOF

# ATHA_000.01 — copy of athena.elf with PS2 ISO naming convention
if [ -f "$BUILD_DIR/athena.elf" ]; then
    cp "$BUILD_DIR/athena.elf" "$BUILD_DIR/ATHA_000.01"
    echo "  Created ATHA_000.01"
fi

# athena.ini — AthenaEnv v4 configuration
cat > "$BUILD_DIR/athena.ini" << 'EOF'
boot_logo = false
dark_mode = true
default_script = "main.js"

# IOP module loading
audsrv = true
EOF

echo ""
echo "=== Build Complete ==="
echo "Output: $BUILD_DIR/"
echo "Files: $(find "$BUILD_DIR" -type f | wc -l)"
